### ISSUE TITLE
Make user prompts more consistent + typos

### ISSUE THREAD

**Issue by Petahhh** [OLRC/SwiftSLOUploader#9]
Ex: 

Do you wish to continue upload 100g at 3.5175879397% ? (yes/no): yes

vs

Do you wish to proceed? Enter yes or no: yes

Typo example:
Starting up load ...

**Comment by cudevmaxwell** [comment]
Forked and fixed. I'm going to test my changes locally, then make a pull request. 
- I changed the command line arguments: replaced underscores with dashes. Is that alright? It will mean a version bump, since we're changing something the user sees or could script against.
- Fixed that typo, and made the user prompts more consistent.
- Use `click.confirm()` where it makes sense. Reduced line count and complexity.

**Comment by cudevmaxwell** [comment]
PR #10

**Comment by Petahhh** [comment]
Fixed by a3bdb1e4811e0a8968ed85545a36ec47172a4121

Thank you Kevin!
